baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
uglyurls = true
relativeURLs = false
title = "Kubernetes学习笔记"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
preserveTaxonomyNames = true
disablePathToLower = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = "c7442f5794ea2abb71c6ff05dc0b8779"

[params]
# General information
    author = "敖小剑"
    keywords = "Kubernetes,k8s,学习笔记,敖小剑"
    description = "Kubernetes学习笔记。"
    copyright = "版权所有，转载请注明出处"
    
    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/skyao/learning-kubernetes"
    
    version = ""
    logo = "images/logo.png"
    favicon = ""
    
    permalink = "#"
    
    # reward button, comment this to disable it
    reward = true
    
    # Custom assets
    custom_css = []
    custom_js  = []
    
    # Syntax highlighting theme
    highlight_css  = ""
    
    [params.palette]
    	primary = "red"
    	accent  = "teal"
    
    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "skyao"
	email   = "aoxiaojian@gmail.com"

[[menu.main]]
	name   = "前言"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "安装"
	identifier = "installation"
	url    = "/installation/"
	weight = 100

[[menu.main]]
	name   = "使用minikube"
	identifier = "installation-minikube"
    parent = "installation"
	url    = "/installation/minikube/"
	weight = 110

[[menu.main]]
	name   = "使用kubeadm"
	identifier = "installation-kubeadm"
    parent = "installation"
	url    = "/installation/kubeadm/"
	weight = 120

[[menu.main]]
	name   = "使用conjure-up"
	identifier = "installation-conjure-up"
    parent = "installation"
	url    = "/installation/conjure-up/"
	weight = 180

[[menu.main]]
	name   = "介绍"
	identifier = "introduction"
	url    = "/introduction/"
	weight = 200

[[menu.main]]
	name   = "概述"
	identifier = "introduction-overview"
	parent = "introduction"
	url    = "/introduction/overview/"
	weight = 210

[[menu.main]]
	name   = "组件"
	identifier = "introduction-component"
	parent = "introduction"
	url    = "/introduction/component/"
	weight = 230

[[menu.main]]
	name   = "API"
	identifier = "introduction-api"
	parent = "introduction"
	url    = "/introduction/api/"
	weight = 240

[[menu.main]]
	name   = "对象"
	identifier = "introduction-object"
	parent = "introduction"
	url    = "/introduction/object/"
	weight = 250

[[menu.main]]
	name   = "概念"
	identifier = "concept"
	url    = "/concept/"
	weight = 300

[[menu.main]]
	name   = "Pod"
	identifier = "concept-pod"
	parent = "concept"
	url    = "/concept/pod/"
	weight = 310

[[menu.main]]
	name   = "Controller"
	identifier = "concept-controller"
	parent = "concept"
	url    = "/concept/controller/"
	weight = 320

[[menu.main]]
	name   = "Service"
	identifier = "concept-service"
	parent = "concept"
	url    = "/concept/service/"
	weight = 330

[[menu.main]]
	name   = "工具"
	identifier = "tool"
	url    = "/tool/"
	weight = 600

[[menu.main]]
	name   = "扩展"
	identifier = "addons"
	url    = "/addons/"
	weight = 500

[[menu.main]]
	name   = "dashboard"
	identifier = "addons-dashboard"
	parent = "addons"
	url    = "/addons/dashboard/"
	weight = 500

[[menu.main]]
	name   = "kubectl"
	identifier = "tool-kubectl"
    parent = "tool"
	url    = "/tool/kubectl/"
	weight = 310

[[menu.main]]
	name   = "多租户"
	identifier = "multitenancy"
	url    = "/multitenancy/"
	weight = 3000


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


